[mypy]
python_version = 3.12
plugins = pydantic.mypy
warn_redundant_casts = True
warn_unused_ignores = True
no_implicit_optional = True

[mypy-cti.core.*]
strict = True

[mypy-cti.manager.*]
strict = True

[mypy-cti.persistence.*]
strict = True

[mypy-cti.plugins.*]
disallow_untyped_defs = False

[mypy-cti.cli.*]
disallow_untyped_defs = False

[mypy-tests.*]
disallow_untyped_defs = False
